---
version: 2

multi-ecosystem-groups:
  tooling:
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      django-stack:
        applies-to: version-updates
        patterns:
          - django
          - django-stubs*
          - pytest-django
      python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - django
          - django-stubs*
          - pytest-django
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directories:
      - "/addons/repairshopr-sync"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

  - package-ecosystem: docker
    directory: "/docker"
    patterns:
      - "*"
    multi-ecosystem-group: tooling
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: tooling
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
